### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by marthammor**
Updated questid for Jewelcrafting items Painter's Pretty Jewel and Lofty Malygite. Added questid for Mining Master Bridgette Holdug and a note on her location. Added the items and order to summon rare Tinnak's Ghost in Azure Span. Added some loot to Tinnak's Ghost.

### CODE REVIEW

**Comment by kemayo** [comment]
I followed this up with 0166be3255f6ea56c701f0c84b8aa58428ce9a50 to clean up some formatting.

**Comment by marthammor** [comment]
I don't know what's up with my formatting, lol. In notepad++ everything looks aligned. Gonna try switching to vscode instead and see if it comes out better.

**Comment by kemayo** [comment]
It's just tabs vs spaces -- it all *looks* okay, but notepad++ isn't noticing what's already in use in the file to be consistent. :D

**Comment by kemayo** [comment]
I added a .editorconfig file in a485e42b45c338726ec13db1c52feef42e609b72 which might help. Depends on whether notepad++ supports it of course. :D

**Comment by marthammor** [comment]
Ah. I usually use vs code for stuff anyway and it looks to be matching what
is in use already. I just had lua files associated to notepad++ yet from
back when I was using it before I found vscode so I was just using it.

**Pull request merged**
